const express = require("express");
const passport = require("passport");
const session = require('express-session');
const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const distance = require('./app/measureDistance.js');
const app = express()
const port = 3000;

//app.get('/', (req, res) => res.send('Hello World!'))

//app.listen(port, () => console.log(`Example app listening on port ${port}!`))
//app.post('/login', passport.authenticate('local', { successRedirect: '/',failureRedirect: '/login' }));

// DISTANCE ========
//(this); //load module containing alghoritm
//distance.loadFile('solvro_city1.json');
//distance.loadFile('test.json');
//console.log(distance.measuredDistances("0"));
//console.log(distance.cityNames());
//console.log(distance.distById("0","0"));

// my not so secret secret
var secret = 'eeeek';

//CONFIGURATION========================
require('./app/config/passport')(passport); // pass passport for configuration
// using body parser to parse the body of incoming post requests
app.use(require('body-parser').urlencoded({
    extended: true // must give a value for extended
}));

// using ejs for rendering
app.set('views', __dirname + '/views');
app.set('view engine', 'ejs');

// using express-session for session cookies
app.use(
    require('express-session')(
        {
            name: 'site_cookie',
            secret: secret,
            resave: false,
            saveUninitialized: false,
            cookie: {
                maxAge: 1500000
            }
        }
    )
);
app.use(passport.initialize());
app.use(passport.session());


//swagger
const options = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
            title: 'JaKDojade in Solvro City',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc',
        },
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./app/routes.js'],
};
const specs = swaggerJsdoc(options);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));

// routes ===========================================
require('./app/routes.js')(app, passport); // load our routes and pass in our app and fully configured passport

app.listen(port, function () {
    console.log('passport-local demo up on port: ' + port);
});
